version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    groups:
      dependencies:
        patterns: ['*']

  - package-ecosystem: bun
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    ignore:
      - dependency-name: '@types/bun'
      - dependency-name: 'typescript'
    groups:
      dependencies:
        patterns: ['*']
